# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e249db3e1d933b19fdbccd2756182545168cb6bd73a35a161fdccc1ef5e474a0486cc6392793cc77354e2137a10d1d660eb41ccae21050f02cd8c80853a5894

test:
  secret_key_base: caf8dd38e12cdd8576b0fefc8007c09c3fd306e6390f0ed58b7bef01b897c22ea4c9be7ca33c944a4df1d1f21979b6785337e934a64d8fb12abbb216bc3725fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
